all: band littleredhen priority swapab threeJobs

band: band.c
	gcc -pthread band.c -o band

littleredhen: littleredhen.c
	gcc -pthread littleredhen.c -o littleredhen

priority: priority.c
	gcc -pthread priority.c -o priority

swapab: swapab.c
	gcc -pthread swapab.c -o swapab

threeJobs: threeJobs.c
	gcc -pthread threeJobs.c -o threeJobs